// This file will be generated by Supabase CLI
// For now, we'll define a minimal Database type that matches our needs

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      pricing_variants: {
        Row: {
          id: string;
          price_key: string;
          brand: string;
          product: string;
          model: string | null;
          base_price_cents: number;
          currency: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          price_key: string;
          brand: string;
          product: string;
          model?: string | null;
          base_price_cents: number;
          currency?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          price_key?: string;
          brand?: string;
          product?: string;
          model?: string | null;
          base_price_cents?: number;
          currency?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      pricing_option_groups: {
        Row: {
          id: string;
          variant_id: string;
          name: string;
          input_type: 'select' | 'numeric_step';
          unit: string | null;
          required: boolean;
          position: number;
          parent_value_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          variant_id: string;
          name: string;
          input_type: 'select' | 'numeric_step';
          unit?: string | null;
          required?: boolean;
          position?: number;
          parent_value_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          variant_id?: string;
          name?: string;
          input_type?: 'select' | 'numeric_step';
          unit?: string | null;
          required?: boolean;
          position?: number;
          parent_value_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      pricing_option_values: {
        Row: {
          id: string;
          group_id: string;
          name: string;
          price_delta_cents: number;
          position: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          group_id: string;
          name: string;
          price_delta_cents?: number;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          group_id?: string;
          name?: string;
          price_delta_cents?: number;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      pricing_numeric_rules: {
        Row: {
          id: string;
          group_id: string;
          value_id: string | null;
          min_value: number;
          max_value: number;
          step_value: number;
          price_per_step_cents: number;
          base_included_value: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          group_id: string;
          value_id?: string | null;
          min_value: number;
          max_value: number;
          step_value: number;
          price_per_step_cents?: number;
          base_included_value?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          group_id?: string;
          value_id?: string | null;
          min_value?: number;
          max_value?: number;
          step_value?: number;
          price_per_step_cents?: number;
          base_included_value?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
